[package]
name = "pptx_indexer"
version = "0.1.0"
authors = ["Teodor Voinea <voinea.teodor@gmail.com>"]
edition = "2018"

[dependencies]
contracts = { path = "../../contracts" }
common = { path = "../../common" }
msoffice_pptx = "0.2.1"
msoffice_shared = "0.1.1"
