name: Test

on: [push]

jobs:
  build:
    name: Test with ${{ matrix.rust_version }} rust on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
#         os: [ubuntu-latest, windows-latest, macos-latest] rust isn't on macos for github yet
        os: [ubuntu-latest, windows-latest]
        rust_version: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@master
    - name: Use ${{ matrix.rust_version }} rust
      run: rustup default ${{ matrix.rust_version }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Install clippy
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
