name: Test

on: 
  pull_request:
    paths-ignore:
      - 'client/**'
      - 'README.md'
      - 'assets/**'

jobs:
  build:
    name: Test with stable rust on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@master
    - name: Use stable rust
      run: rustup default stable
    - name: Install rustfmt
      run: rustup component add rustfmt
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Install clippy
      run: rustup component add clippy
#    - name: Run clippy
#      if: matrix.rust_version == 'stable'
#      run: cargo clippy --all-targets --all-features -- -D warnings
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose --workspace --no-fail-fast
    