name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        rust_version: [stable, beta, nightly]

    steps:
    - uses: actions/checkout@master
    - name: Use ${{ matrix.rust_version }} rust
      run: rustup default ${{ matrix.rust_version }}
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Run fmt
      run: cargo fmt --all -- --check
    - name: Run clippy
      run: cargo clippy --all-targets --all-features -- -D warnings
